amount_a = ""
amount_b = ""
chain_id = ""
commitment_a = ""
commitment_b = ""
expiry_block_a = ""
expiry_block_b = ""
fill_amount = ""
fill_receipt = ""
market_id = ""
match_nonce = ""
owner_id_a = ""
owner_id_b = ""
price_a = ""
price_b = ""
salt_a = ""
salt_b = ""
settlement_price = ""
side_a = ""
side_b = ""
