amount = ""
balance = ""
balance_leaf_index = ""
balance_leaf_nonce = ""
balance_merkle_path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
balance_root = ""
base_token = ""
chain_id = ""
commitment = ""
expiry_block = ""
market_id = ""
nullifier = ""
owner_id = ""
price = ""
quote_token = ""
salt = ""
sender_secret = ""
side = ""
