// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import { OrderCommitmentVerifier } from "../src/verifiers/OrderCommitmentVerifier.sol";
import { MatchProofVerifier } from "../src/verifiers/MatchProofVerifier.sol";
import { BalanceUpdateVerifier } from "../src/verifiers/BalanceUpdateVerifier.sol";
import { Vault } from "../src/Vault.sol";
import { DarkBookEngine } from "../src/DarkBookEngine.sol";

/// @notice End-to-end test that proves the on-chain verifier accepts a real
///         UltraHonk proof produced from the `darkbook_order_commitment`
///         circuit by `circuits/scripts/gen-fixtures.sh`.
///
///         The fixture binaries live under `contracts/test/fixtures/order_commitment/`
///         and are regenerated by running that script after any circuit change.
///
///         The vault's balance Merkle root is set via `vm.store` so it matches
///         the root the proof was generated against. In production the matcher
///         is responsible for proving against the *current* vault root; for a
///         single-shot test fixture, injecting the root is the practical move.
contract OrderCommitmentProofTest is Test {
    // Storage slot of `balanceTree.root` inside `Vault`.
    // Layout: balanceTree is the first state var; the MerkleTree.Tree struct is:
    //   nextLeafIndex (uint256)            -> slot 0
    //   filledSubtrees (bytes32[20])       -> slots 1..20
    //   root (bytes32)                     -> slot 21
    uint256 internal constant VAULT_ROOT_SLOT = 21;

    OrderCommitmentVerifier orderVerifier;
    MatchProofVerifier matchVerifier;
    BalanceUpdateVerifier balanceVerifier;
    Vault vault;
    DarkBookEngine engine;

    // Fixture values -- must match what `print_fixture_values` in the
    // order_commitment circuit prints. Keeping them inline (rather than
    // parsing from a JSON file) gives the test a single source of truth.
    bytes32 constant FIX_COMMITMENT    = 0x0a6c2196b8445b12dfd50212382eea56db8cf395f6290838234206fc0234a0c4;
    bytes32 constant FIX_NULLIFIER     = 0x2d4cddf1a51904a47fc66f3e73e20356cdf3f0f4712497dbc81c38a74b52e385;
    bytes32 constant FIX_BALANCE_ROOT  = 0x1fd357b38a122063e6609acef276ec1117f88070dcb308ac56f38327ab3803f0;
    bytes32 constant FIX_OWNER_ID      = 0x0221e4b4837371040a10fe17b9a4ab5923592881cda453ff85bfe74c22f859ad;
    uint256 constant FIX_MARKET_ID     = 1;
    uint256 constant FIX_EXPIRY_BLOCK  = 100_000;
    // The circuit's chain_id is hardcoded to 31337 (Foundry default).

    function setUp() public {
        orderVerifier = new OrderCommitmentVerifier();
        matchVerifier = new MatchProofVerifier();
        balanceVerifier = new BalanceUpdateVerifier();
        vault = new Vault();
        engine = new DarkBookEngine(
            address(orderVerifier),
            address(matchVerifier),
            address(balanceVerifier),
            address(vault)
        );
        vault.setDarkBookEngine(address(engine));

        // Inject the fixture's balance root into the vault so the proof's
        // public input matches what the engine reads.
        vm.store(address(vault), bytes32(VAULT_ROOT_SLOT), FIX_BALANCE_ROOT);
        require(vault.getBalanceRoot() == FIX_BALANCE_ROOT, "root injection failed");

        // Foundry's default chain id is 31337, matching the fixture.
        require(block.chainid == 31337, "unexpected chain id");
    }

    /// @notice Submit an order using a real UltraHonk proof. This is the
    ///         positive case the stub verifier could never test, because
    ///         the stub returned `true` for any bytes.
    function test_submitOrder_accepts_real_proof() public {
        bytes memory proof = vm.readFileBinary("test/fixtures/order_commitment/proof");
        assertEq(proof.length, 8384, "fixture proof unexpected size");

        // matcher == address(this); we authorised ourselves below in setUp
        // implicitly because the deployer of the engine is the test contract.

        engine.submitOrder(
            FIX_COMMITMENT,
            FIX_NULLIFIER,
            FIX_OWNER_ID,
            FIX_MARKET_ID,
            FIX_EXPIRY_BLOCK,
            proof
        );

        DarkBookEngine.OrderCommitment memory stored = engine.getOrder(FIX_COMMITMENT);
        assertEq(stored.commitment, FIX_COMMITMENT);
        assertEq(stored.ownerId, FIX_OWNER_ID);
        assertEq(stored.marketId, FIX_MARKET_ID);
        assertTrue(stored.status == DarkBookEngine.OrderStatus.Active);
        assertTrue(engine.isNullifierUsed(FIX_NULLIFIER));
    }

    /// @notice Mutate the proof by a single bit and confirm the verifier
    ///         rejects it. This is the tightest soundness check we can run
    ///         locally without re-proving.
    function test_submitOrder_rejects_tampered_proof() public {
        bytes memory proof = vm.readFileBinary("test/fixtures/order_commitment/proof");
        // Flip a bit deep inside the proof body (avoid the public-input
        // prefix which would surface as a different revert path).
        proof[5000] = proof[5000] ^ 0x01;

        vm.expectRevert();
        engine.submitOrder(
            FIX_COMMITMENT,
            FIX_NULLIFIER,
            FIX_OWNER_ID,
            FIX_MARKET_ID,
            FIX_EXPIRY_BLOCK,
            proof
        );
    }

    /// @notice Tampering with a public input (e.g. claiming a different
    ///         market) must also be rejected: the proof was generated for
    ///         market_id = 1, so submitting it as market_id = 2 changes the
    ///         public-input vector and the verifier rejects.
    function test_submitOrder_rejects_wrong_market() public {
        bytes memory proof = vm.readFileBinary("test/fixtures/order_commitment/proof");

        vm.expectRevert();
        engine.submitOrder(
            FIX_COMMITMENT,
            FIX_NULLIFIER,
            FIX_OWNER_ID,
            FIX_MARKET_ID + 1, // wrong market
            FIX_EXPIRY_BLOCK,
            proof
        );
    }
}
