#!/usr/bin/env bash
# ============================================================
# DarkBook end-to-end demo
# ============================================================
# Walks the whole ZK pipeline with one command and real proofs:
#
#   1. Noir circuits          -- 58 tests
#   2. Proof fixtures         -- 3 real UltraHonk proofs generated by bb
#   3. On-chain verification  -- the three generated Solidity verifiers
#      accept the real proofs; the full settleMatch path runs end-to-end
#   4. Matcher prover         -- generates real proofs off-chain and
#      round-trips them through `bb verify`
#
# Nothing here is mocked: every proof is a real UltraHonk proof and every
# verification is the real verifier. Run from the repo root.
#
# Prerequisites: nargo, bb, forge, node (>=20).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

bold()  { printf '\033[1m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }
step()  { printf '\n\033[1;36m==> %s\033[0m\n' "$1"; }

need() {
    command -v "$1" >/dev/null 2>&1 || {
        printf '\033[31mmissing required tool: %s\033[0m\n' "$1" >&2
        exit 1
    }
}
need nargo
need bb
need forge
need node

bold "DarkBook -- end-to-end ZK demo"
echo  "Repo: $ROOT"

# ------------------------------------------------------------
step "1/4  Noir circuits -- nargo test --workspace"
( cd circuits && nargo test --workspace )
green "circuits: all tests passed"

# ------------------------------------------------------------
step "2/4  Proof fixtures -- generating real UltraHonk proofs"
# Verifiers must exist for the vks the fixture script consumes.
if [ ! -d circuits/target/vk ]; then
    echo "  generating verifiers + vks (first run)..."
    bash circuits/scripts/codegen-verifiers.sh >/dev/null
fi
bash circuits/scripts/gen-fixtures.sh
green "fixtures: 3 real proofs generated and natively verified"

# ------------------------------------------------------------
step "3/4  On-chain verification -- forge test (real proofs)"
( cd contracts && forge test --skip lint \
    --match-contract "OrderCommitmentProofTest|MatchProofFixtureTest|BalanceUpdateFixtureTest|CompileTest" \
    -vv )
green "contracts: real proofs verified on-chain; full settleMatch path runs"

# ------------------------------------------------------------
step "4/4  Matcher prover -- generate + verify off-chain"
( cd matcher && npx vitest run tests/prover.test.ts )
green "matcher: generates all three proofs, each round-trips through bb verify"

# ------------------------------------------------------------
printf '\n'
bold "Demo complete."
cat <<'SUMMARY'

  What just ran, with zero mocks:
    - 58 Noir circuit tests
    - 3 real UltraHonk proofs (order_commitment, match_proof, balance_update)
    - on-chain acceptance by the 3 generated Solidity verifiers
    - the full DarkBookEngine.settleMatch path with a real match proof
      AND a real balance_update proof
    - the matcher generating those same proofs off-chain

  Still stubbed (see README roadmap):
    - browser-side proving needs the in-browser Pedersen derivation layer
    - the autonomous matcher needs a balance-tree mirror

SUMMARY
