base_token = ""
commitment_a = ""
commitment_b = ""
fill_amount = ""
fill_receipt = ""
leaf_index_base_a = ""
leaf_index_base_b = ""
leaf_index_quote_a = ""
leaf_index_quote_b = ""
match_nonce = ""
mid_root = ""
new_leaf_nonce_base_a = ""
new_leaf_nonce_base_b = ""
new_leaf_nonce_quote_a = ""
new_leaf_nonce_quote_b = ""
new_root = ""
old_base_a = ""
old_base_b = ""
old_leaf_nonce_base_a = ""
old_leaf_nonce_base_b = ""
old_leaf_nonce_quote_a = ""
old_leaf_nonce_quote_b = ""
old_quote_a = ""
old_quote_b = ""
old_root = ""
owner_id_a = ""
owner_id_b = ""
path_base_a_in_old = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
path_base_b_in_old = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
path_quote_a_in_mid = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
path_quote_b_in_mid = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
quote_token = ""
settlement_price = ""
side_a = ""
