// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title DarkBookEngine
/// @notice Core orderbook -- stores opaque order commitments, manages the
///         order lifecycle, and settles matches against three UltraHonk
///         verifiers (one per circuit: order_commitment, match_proof,
///         balance_update). The engine never sees plaintext order
///         parameters; every constraint is proved off-chain in Noir.

interface IVault {
    function getBalanceRoot() external view returns (bytes32);
    function updateBalanceRoot(bytes32 newRoot) external;
}

/// @dev Minimal interface every UltraHonk verifier generated by
///      `bb write_solidity_verifier` exposes. The Solidity-level contract
///      type is per-circuit (`OrderCommitmentVerifier`, etc.) but the
///      engine treats them uniformly.
interface IHonkVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs)
        external
        view
        returns (bool);
}

contract DarkBookEngine {
    // ============================================================
    //                         TYPES
    // ============================================================

    enum OrderStatus {
        None,        // 0 - does not exist
        Active,      // 1 - submitted and verified
        Filled,      // 2 - fully filled via match
        PartialFill, // 3 - partially filled
        Cancelled    // 4 - cancelled by owner
    }

    struct OrderCommitment {
        bytes32 commitment;      // Pedersen hash binding all order params
        address owner;           // EOA that submitted on-chain
        bytes32 ownerId;         // private-identity hash (public input on the proof)
        uint256 marketId;        // trading pair
        uint256 expiryBlock;     // order auto-expires after this block
        uint256 epoch;           // submission epoch
        uint256 timestamp;       // block timestamp at submission
        OrderStatus status;
        uint256 remainingAmount; // partial-fill tracking (engine space)
    }

    struct SettlementRecord {
        bytes32 commitmentA;
        bytes32 commitmentB;
        bytes32 fillReceipt;
        uint256 settlementPrice;
        uint256 timestamp;
    }

    // ============================================================
    //                          STATE
    // ============================================================

    IHonkVerifier public immutable orderVerifier;
    IHonkVerifier public immutable matchVerifier;
    IHonkVerifier public immutable balanceVerifier;
    IVault public immutable vault;

    address public owner;
    uint256 public epochCounter;
    bool public permissionedMatching;

    mapping(bytes32 => OrderCommitment) public commitments;
    mapping(bytes32 => bool) public nullifiers;
    mapping(uint256 => uint256) public activeCommitmentCount;
    mapping(uint256 => bytes32[]) public pairCommitments;
    SettlementRecord[] public settlements;
    mapping(address => bool) public authorizedMatchers;

    /// @notice Fill receipts already settled. The match_proof + balance_update
    ///         pair binds to a single (match_id, fill, price) tuple via the
    ///         fill_receipt public input. Recording it here prevents the
    ///         same match from being settled twice even if the proofs are
    ///         resubmitted verbatim.
    mapping(bytes32 => bool) public spentFillReceipts;

    // ============================================================
    //                          EVENTS
    // ============================================================

    event OrderSubmitted(
        bytes32 indexed commitment,
        address indexed owner,
        uint256 indexed marketId,
        uint256 epoch,
        uint256 timestamp
    );

    event OrderCancelled(
        bytes32 indexed commitment,
        address indexed owner,
        uint256 timestamp
    );

    event MatchSettled(
        bytes32 indexed commitmentA,
        bytes32 indexed commitmentB,
        bytes32 indexed fillReceipt,
        uint256 settlementPrice,
        bytes32 oldRoot,
        bytes32 newRoot,
        uint256 timestamp
    );

    event EpochAdvanced(uint256 newEpoch);
    event MatcherAuthorized(address indexed matcher);
    event MatcherRevoked(address indexed matcher);

    // ============================================================
    //                         ERRORS
    // ============================================================

    error Unauthorized();
    error InvalidProof();
    error NullifierAlreadyUsed();
    error CommitmentAlreadyExists();
    error CommitmentNotFound();
    error CommitmentNotActive();
    error NotCommitmentOwner();
    error InvalidMarket();
    error MatcherNotAuthorized();
    error MarketMismatch();
    error FillReceiptAlreadySpent();
    error OrderExpired();
    error StaleBalanceRoot();

    // ============================================================
    //                        MODIFIERS
    // ============================================================

    modifier onlyOwner() {
        if (msg.sender != owner) revert Unauthorized();
        _;
    }

    modifier onlyAuthorizedMatcher() {
        if (permissionedMatching && !authorizedMatchers[msg.sender]) {
            revert MatcherNotAuthorized();
        }
        _;
    }

    // ============================================================
    //                       CONSTRUCTOR
    // ============================================================

    constructor(
        address _orderVerifier,
        address _matchVerifier,
        address _balanceVerifier,
        address _vault
    ) {
        owner = msg.sender;
        orderVerifier = IHonkVerifier(_orderVerifier);
        matchVerifier = IHonkVerifier(_matchVerifier);
        balanceVerifier = IHonkVerifier(_balanceVerifier);
        vault = IVault(_vault);
        epochCounter = 1;
        permissionedMatching = true;
    }

    // ============================================================
    //                     ADMIN FUNCTIONS
    // ============================================================

    function authorizeMatcher(address matcher) external onlyOwner {
        authorizedMatchers[matcher] = true;
        emit MatcherAuthorized(matcher);
    }

    function revokeMatcher(address matcher) external onlyOwner {
        authorizedMatchers[matcher] = false;
        emit MatcherRevoked(matcher);
    }

    function setPermissionedMatching(bool _permissioned) external onlyOwner {
        permissionedMatching = _permissioned;
    }

    function advanceEpoch() external onlyOwner {
        epochCounter++;
        emit EpochAdvanced(epochCounter);
    }

    // ============================================================
    //                    ORDER SUBMISSION
    // ============================================================

    /// @notice Submit a new order commitment with an order_commitment proof.
    /// @param commitment   Pedersen hash binding chain_id, market_id, owner_id,
    ///                     price, amount, side, expiry_block, salt.
    /// @param nullifier    H(DST, chain_id, market_id, sender_secret, salt).
    ///                     Used once per (sender_secret, salt) per market.
    /// @param ownerId      Owner-identity hash; public input on the proof.
    ///                     The engine stores it so subsequent flows
    ///                     (cancellation, match) can rebind to it.
    /// @param marketId     Trading pair identifier. Must be non-zero.
    /// @param expiryBlock  Block number after which this order is no longer
    ///                     settleable. Bound by the commitment.
    /// @param proof        UltraHonk proof bytes for `darkbook_order_commitment`.
    function submitOrder(
        bytes32 commitment,
        bytes32 nullifier,
        bytes32 ownerId,
        uint256 marketId,
        uint256 expiryBlock,
        bytes calldata proof
    ) external {
        if (marketId == 0) revert InvalidMarket();
        if (nullifiers[nullifier]) revert NullifierAlreadyUsed();
        if (commitments[commitment].status != OrderStatus.None) revert CommitmentAlreadyExists();
        if (expiryBlock <= block.number) revert OrderExpired();

        bytes32 balanceRoot = vault.getBalanceRoot();

        // Public inputs MUST match the Noir circuit's `pub` declaration order:
        // commitment, nullifier, balance_root, owner_id, chain_id, market_id, expiry_block.
        bytes32[] memory publicInputs = new bytes32[](7);
        publicInputs[0] = commitment;
        publicInputs[1] = nullifier;
        publicInputs[2] = balanceRoot;
        publicInputs[3] = ownerId;
        publicInputs[4] = bytes32(block.chainid);
        publicInputs[5] = bytes32(marketId);
        publicInputs[6] = bytes32(expiryBlock);

        if (!orderVerifier.verify(proof, publicInputs)) revert InvalidProof();

        nullifiers[nullifier] = true;

        commitments[commitment] = OrderCommitment({
            commitment: commitment,
            owner: msg.sender,
            ownerId: ownerId,
            marketId: marketId,
            expiryBlock: expiryBlock,
            epoch: epochCounter,
            timestamp: block.timestamp,
            status: OrderStatus.Active,
            remainingAmount: 0
        });

        pairCommitments[marketId].push(commitment);
        activeCommitmentCount[marketId]++;

        emit OrderSubmitted(commitment, msg.sender, marketId, epochCounter, block.timestamp);
    }

    // ============================================================
    //                    ORDER CANCELLATION
    // ============================================================

    /// @notice Cancel an active order. Ownership is checked against the
    ///         EOA that submitted. A future revision will replace this
    ///         with a ZK proof of salt knowledge so the engine doesn't
    ///         link orders to addresses at cancellation time.
    function cancelOrder(bytes32 commitment) external {
        OrderCommitment storage order = commitments[commitment];

        if (order.status == OrderStatus.None) revert CommitmentNotFound();
        if (order.status != OrderStatus.Active && order.status != OrderStatus.PartialFill) {
            revert CommitmentNotActive();
        }
        if (order.owner != msg.sender) revert NotCommitmentOwner();

        order.status = OrderStatus.Cancelled;
        activeCommitmentCount[order.marketId]--;

        emit OrderCancelled(commitment, msg.sender, block.timestamp);
    }

    // ============================================================
    //                    MATCH SETTLEMENT
    // ============================================================

    /// @notice Settle a match between two committed orders.
    ///         The matcher supplies the match_proof + balance_update_proof
    ///         pair, both binding the same `fillReceipt`.
    /// @param commitA          First order's commitment.
    /// @param commitB          Second order's commitment.
    /// @param fillReceipt      H(DST_FILL, match_id, fill_amount, settlement_price).
    /// @param settlementPrice  Public settlement price (bound by both proofs).
    /// @param midRoot          Intermediate balance root (after base-leaf update).
    /// @param newRoot          Final balance root (after quote-leaf update).
    /// @param matchProof       UltraHonk proof for `darkbook_match_proof`.
    /// @param balanceProof     UltraHonk proof for `darkbook_balance_update`.
    function settleMatch(
        bytes32 commitA,
        bytes32 commitB,
        bytes32 fillReceipt,
        uint256 settlementPrice,
        bytes32 midRoot,
        bytes32 newRoot,
        bytes calldata matchProof,
        bytes calldata balanceProof
    ) external onlyAuthorizedMatcher {
        OrderCommitment storage orderA = commitments[commitA];
        OrderCommitment storage orderB = commitments[commitB];

        if (orderA.status != OrderStatus.Active && orderA.status != OrderStatus.PartialFill) {
            revert CommitmentNotActive();
        }
        if (orderB.status != OrderStatus.Active && orderB.status != OrderStatus.PartialFill) {
            revert CommitmentNotActive();
        }
        if (orderA.marketId != orderB.marketId) revert MarketMismatch();
        if (spentFillReceipts[fillReceipt]) revert FillReceiptAlreadySpent();
        if (block.number > orderA.expiryBlock || block.number > orderB.expiryBlock) {
            revert OrderExpired();
        }

        bytes32 oldRoot = vault.getBalanceRoot();

        // match_proof public inputs (6, in Noir declaration order):
        // commitment_a, commitment_b, fill_receipt, settlement_price, market_id, chain_id.
        bytes32[] memory matchInputs = new bytes32[](6);
        matchInputs[0] = commitA;
        matchInputs[1] = commitB;
        matchInputs[2] = fillReceipt;
        matchInputs[3] = bytes32(settlementPrice);
        matchInputs[4] = bytes32(orderA.marketId);
        matchInputs[5] = bytes32(block.chainid);
        if (!matchVerifier.verify(matchProof, matchInputs)) revert InvalidProof();

        // balance_update public inputs (5):
        // old_root, mid_root, new_root, fill_receipt, settlement_price.
        bytes32[] memory balanceInputs = new bytes32[](5);
        balanceInputs[0] = oldRoot;
        balanceInputs[1] = midRoot;
        balanceInputs[2] = newRoot;
        balanceInputs[3] = fillReceipt;
        balanceInputs[4] = bytes32(settlementPrice);
        if (!balanceVerifier.verify(balanceProof, balanceInputs)) revert InvalidProof();

        spentFillReceipts[fillReceipt] = true;
        vault.updateBalanceRoot(newRoot);

        orderA.status = OrderStatus.Filled;
        orderB.status = OrderStatus.Filled;
        activeCommitmentCount[orderA.marketId] -= 2;

        settlements.push(SettlementRecord({
            commitmentA: commitA,
            commitmentB: commitB,
            fillReceipt: fillReceipt,
            settlementPrice: settlementPrice,
            timestamp: block.timestamp
        }));

        emit MatchSettled(
            commitA, commitB, fillReceipt, settlementPrice, oldRoot, newRoot, block.timestamp
        );
    }

    // ============================================================
    //                     VIEW FUNCTIONS
    // ============================================================

    function getActiveCommitmentCount(uint256 marketId) external view returns (uint256) {
        return activeCommitmentCount[marketId];
    }

    function getPairCommitments(uint256 marketId) external view returns (bytes32[] memory) {
        return pairCommitments[marketId];
    }

    function getSettlementCount() external view returns (uint256) {
        return settlements.length;
    }

    function getOrder(bytes32 commitment) external view returns (OrderCommitment memory) {
        return commitments[commitment];
    }

    function isNullifierUsed(bytes32 nullifier) external view returns (bool) {
        return nullifiers[nullifier];
    }
}
